### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by ohacy** [EsupPortail/esup-mdw-pegase#14]
Bonjour, 
Dans le dockerfile, quel doit être la valeur de l'ENTRYPOINT ? 

En laissant 'fr.univlorraine.**blank**.Application', la class n'est pas trouvée lors du run de l'image docker. 

```Error: Could not find or load main class fr.univlorraine.blank.Application
Caused by: java.lang.ClassNotFoundException: fr.univlorraine.blank.Application
```

Si je remplace la classe par 'fr.univlorraine.mondossierweb.Application', java n'arrive pas à parser la class, voici les logs du run de l'image : 

```
2021-11-30 15:24:51.487 user:NO_USER     INFO 1 --- [           main] f.u.mondossierweb.Application            : Starting Application on mdw-75bc66b4cc-pnz7q with PID 1 (/app started by root in /)
2021-11-30 15:24:51.489 user:NO_USER     INFO 1 --- [           main] f.u.mondossierweb.Application            : No active profile set, falling back to default profiles: default
2021-11-30 15:24:51.490 user:NO_USER    DEBUG 1 --- [           main] o.s.boot.SpringApplication               : Loading source class fr.univlorraine.mondossierweb.Application
2021-11-30 15:24:51.546 user:NO_USER    DEBUG 1 --- [           main] o.s.b.c.c.ConfigFileApplicationListener  : Loaded config file 'file:/app/application.properties' (classpath:/application.properties)
2021-11-30 15:24:51.911 user:NO_USER     WARN 1 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [fr.univlorraine.mondossierweb.Application]; nested exception is java.lang.IllegalStateException: Failed to introspect annotated methods on class org.springframework.boot.web.servlet.support.SpringBootServletInitializer
2021-11-30 15:24:51.917 user:NO_USER    DEBUG 1 --- [           main] .c.l.ClasspathLoggingApplicationListener : Application failed to start with classpath: unknown
2021-11-30 15:24:51.927 user:NO_USER    ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
```

Le contenu du Dockerfile : 

```
FROM maven:3.8.1-jdk-11 AS builder
WORKDIR /build
COPY pom.xml /build/
COPY src /build/src
COPY frontend /build/frontend
RUN mvn -Pmaven-frontend -Pproduction --batch-mode --errors --show-version package

FROM openjdk:11-jdk-slim
VOLUME /tmp
COPY --from=builder /build/target/webapp/WEB-INF/lib /app/lib
COPY --from=builder /build/target/webapp/META-INF /app/META-INF
COPY --from=builder /build/target/webapp/WEB-INF/classes /app
ENTRYPOINT ["java","-cp","app:app/lib/*","fr.univlorraine.mondossierweb.Application"] 
```

Merci par avance, 
Cyril Ohanian, PC-SCOL

**Comment by bquiller** [comment]
Bonjour,

Il faut mettre cela :
ENTRYPOINT ["java","-cp","app:app/lib/*","fr.univlorraine.mondossierweb.Application"]

**Comment by cdubois54** [comment]
Bonjour, 

toutes mes excuses car le dockerfile n'étant pas fonctionnel, il n'aurait pas dû être publié sur git, ni livré.
C'est un reliquat et une base de travail pour une future version.

Cordialement

**Comment by pippobimbo** [comment]
Bonjour,

Je rebondis sur ce sujet quelques années après car j'essaie de mettre en place "mondossierweb" au sein de notre établissement.

Je ne suis pas très doué avec Docker mais j'ai essayé de m'inspirer de vos échanges afin d'avoir un Dockerfile fonctionnel:

```
# Stage that builds the application, a prerequisite for the running stage
FROM maven:3.8.5-openjdk-17-slim AS build
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get update -qq && apt-get install -qq --no-install-recommends nodejs

# Stop running as root at this point
RUN useradd -m myuser
WORKDIR /usr/src/app/
RUN chown myuser:myuser /usr/src/app/
USER myuser

# Copy pom.xml and prefetch dependencies so a repeated build can continue from the next step with existing dependencies
COPY --chown=myuser pom.xml ./
RUN mvn dependency:go-offline -Pproduction

# Copy all needed project files to a folder
COPY --chown=myuser:myuser src src
COPY --chown=myuser:myuser frontend frontend
COPY --chown=myuser:myuser package.json ./

# Build the production package, assuming that we validated the version before so no need for running tests again
RUN mvn clean package -DskipTests -Pproduction

# Running stage: the part that is used for running the application
FROM tomcat:jdk17
COPY --from=build /usr/src/app/target/*.war /usr/local/tomcat/webapps/ROOT.war
EXPOSE 8080
WORKDIR /usr/app/
ENTRYPOINT ["catalina.sh", "run"]

```


L'image a été créée avec succès.

J'ai ajouté la start-class ci-dessous dans le fichier "pom.xml" car j'avais une erreur par la suite:

```
<properties>
		<start-class>fr.univlorraine.mondossierweb.Application</start-class>
		<revision>2.2.1</revision>
		<sha1></sha1>
		<changelist>-SNAPSHOT</changelist>
		<java.version>17</java.version>
		<!-- <vaadin.version>24.0.5</vaadin.version> -->
		<vaadin.version>24.3.3</vaadin.version>
		<gson-fire-version>1.8.4</gson-fire-version>
        <swagger-core-version>1.5.24</swagger-core-version>
        <okhttp-version>4.9.3</okhttp-version>
        <gson-version>2.8.6</gson-version>
        <commons-lang3-version>3.10</commons-lang3-version>
        <javax-annotation-version>1.3.2</javax-annotation-version>
        <h2.version>2.1.210</h2.version>
  		<sonar.qualitygate.wait>true</sonar.qualitygate.wait>
  		<skipITs>false</skipITs>
  		<flyway.version>8.5.13</flyway.version>
	</properties> 
```

J'ai ensuite utilisé le docker-compose ci-dessous:

```
services:

  mariadb:
    image: mariadb:10.8.2
    restart: always
    container_name: mariadb
    volumes:
      - /home/thierry/docker/mariadb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=mypass
      - MARIADB_DATABASE=mdw
      - MARIADB_ROOT_HOST=%
    networks:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
    networks:
      - app

  mdw-pegase:
    image: esup-mdw:latest
    container_name: mdw-pegase
    ports:
      - 8080:8080
    volumes:
      - /home/thierry/docker/esup-mdw-pegase:/config
    environment:
      JAVA_OPTS: -Dspring.config.location=file:/config/application.properties
    depends_on:
      - mariadb
    networks:
      - app

networks:
  app:
    driver: bridge
```

J'ai ensuite déposé le fichier "application.properties" dans le répertoire "config" avec la chaine de connexion ci-dessous:

```
# MySQL
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://mariadb:3306/mdw?serverTimezone=Europe/Paris
spring.datasource.username = root
spring.datasource.password = mypass
```

Et c'est donc au moment du lancement du container "mdw-pegase" que les ennuies comment avec cette erreur:

`java.sql.SQLException: Access denied for user 'root'@'172.18.0.4' (using password: YES)`

J'arrive bien à me connecter sur la BdD MariaDB avec root/mypass depuis PHPMyAdmin et le root semble avoir les accès requis:

<img width="873" alt="image" src="https://github.com/user-attachments/assets/c270b910-c781-44c4-b79c-79c1567e73f2">

Est-ce que quelqu'un aurait déjà rencontré ce problème svp?

Merci par avance pour vos réponses,
Thierry
